### ISSUE TITLE
Missing LICENCE information

### ISSUE THREAD

**Issue by peterjc** [pkerpedjiev/forna#27]
I could not see which licence you are using in the README file, nor is a LICENSE file present as GitHub suggest: https://help.github.com/articles/open-source-licensing/

**Comment by j-4** [comment]
I think this is fixed already, please feel free to re-open in case it is not!
Thanks for your comment!

**Comment by peterjc** [comment]
Agreed, https://github.com/pkerpedjiev/forna/commit/3b7d7093d4067cc89727dbe83feb612cd723128a added a ``LICENSE`` file (Apache License, Version 2.0).

This is much clearer now, thank you.
