### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by mnori** [pkerpedjiev/forna#33]
Am really liking forna. I integrated it into some of my own work.

I'm currently writing a manuscript and am wondering if there is a paper I can cite that covers forna.

Thanks, Matt

**Comment by pkerpedjiev** [comment]
Thank you kindly! Glad you hear you like it!

http://nibiru.tbi.univie.ac.at/forna/citation.html

To save you the trouble the bibtex is here (taken from the oxford journals web site):

@article{Kerpedjiev15102015,
author = {Kerpedjiev, Peter and Hammer, Stefan and Hofacker, Ivo L.}, 
title = {Forna (force-directed RNA): Simple and effective online RNA secondary structure diagrams},
volume = {31}, 
number = {20}, 
pages = {3377-3379}, 
year = {2015}, 
doi = {10.1093/bioinformatics/btv372}, 
URL = {http://bioinformatics.oxfordjournals.org/content/31/20/3377.abstract}, 
eprint = {http://bioinformatics.oxfordjournals.org/content/31/20/3377.full.pdf+html}, 
journal = {Bioinformatics} 
}

**Comment by mnori** [comment]
Thank you :)
Matt
